# Generated by Django 5.1.5 on 2025-02-05 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweetapp', '0002_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='thumnail',
            new_name='thumbnail',
        ),
    ]
